### ISSUE TITLE
Can a user resubmit the same workflow twice?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#103]
This issue came about during work on logging. As of https://github.com/fractal-analytics-platform/fractal-server/issues/97#issuecomment-1268129032, resubmitting the same workflow twice would lead to a mix-up of logs in the same folder (since this is made unique via the workflow ID).

Broader question: is re-submitting the same workflow something a user will ever do?
* If yes, we should make sure that logging is handled correctly (and think about other potential issues).
* If not, let's forbid it  explicitly, e.g. by adding a `already_submitted=True/False` attribute to `Task` objects and db entries.

**Comment by jluethi** [comment]
The answer to this is "it depends" on what exactly we mean with resubmit the same workflow twice. I don't think it makes sense to just rerun a successful workflow on the same data. But:

1) A user may want to resubmit a workflow with changed parameters (technically still the same workflow, just modified)
2) A user will want to resubmit a workflow that has failed (though likely not from the beginning, only from where it has failed => may be a separate workflow under the hood). The main part here is that only tasks that haven't run should be rerun. But the task that failed was submitted, but didn't finish. That is trickier anyway, let's discuss tomorrow
3) A user may submit a workflow on a small subset of the data for test purposes and then submit the same workflow on the full dataset later (=> that should be allowed) 

=> maybe the unique part should be "Has this input data been processed with this task and these existing parameters"?
Alternatively, just a "has this dataset been processed with this task", but allow for a rerun because the user may change parameters.

**Comment by jluethi** [comment]
Hmm, I think we need to separate 2 cases here:
1) Resubmitting a workflow as in "continue from where you left off" => see my comments above for the scenarios
2) Resubmitting a workflow as in "I want to rerun the whole processing from the start" (I think that is what you are describing @gusqgm )

For case 2, I would think:
Rerunning a workflow from the start should raise a warning that this will delete existing data. The way around this would be to change the dataset output. This could be in the warning, e.g.:
> Rerunning the full workflow will overwrite the existing OME-Zarr. To keep the existing Zarr, change the output-dataset of the workflow.

One question on nomenclature:
How do we differentiate between rerunning and continuing? My suggestion would be to not use "resubmit", but to use distinct terms:
1) Resume Workflow
2) Rerun Workflow

**Comment by tcompa** [comment]
Thanks to both of you for the feedback.
This resume/rerun feature of the server is not yet being implemented (v1.x will make it easier to handle, in any form we'd design it), but we'll come back to this issue as soon as we look at it.

**Comment by jacopo-exact** [comment]
it should be partly solved in 1.x, where each run works in a separate folder with a unique `job_id`.

TODO: add test to verify this.

**Comment by jluethi** [comment]
Logs got mixed. Now it should be solved.
