### ISSUE TITLE
Prevent task-package name conflict

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1189]
Related to #736.

If we trigger task collection of both `fractal-tasks-core` and `fractal_tasks_core`, as of #1188 the two will have a name conflict, since they both map to the same normalized package name.

Existence of the target folder should be checked within the endpoint, with the appropriate 422 error raised if needed.

**Comment by jluethi** [comment]
We also did some handling or cleanup in some failure states, no?

When debugging with Enrico & Franzi on Tuesday, I had one issue where I couldn't trigger collection anymore because the output folder already existed. But I vaguely remember that sometime, I could rerun a failed collection. Was that because the collection cleaned up after itself when failing? Or the new collection cleaning up before it starts installing the venv?

**Comment by jluethi** [comment]
Great, thanks for the summary!
