### ISSUE TITLE
introduce workflow datastructure

### ISSUE THREAD

**Issue by jacopo-exact** [fractal-analytics-platform/fractal-server#131]
workflow will constitute the single nesting level possible.

two ways out:
1. lean structure with just a text field that directly translates to an exportable representation of the workflow
  * pro: simple
  * con: no validation of the existence of linked tasks
2. relational workflow
  * pro: validation of relations
  * con: a little extra work to import / export

**Comment by tcompa** [comment]
I'm not sure whether they are relevant for the pro/con assessment, but other desired functionalities (apart from import/export) are:
* Is it simple to concatenate two workflows, or to remove some tasks from a workflow?
* Is it simple to run a subpart of a workflow (e.g. "only re-run tasks from 3 to 10, because 1&2 succeeded but 3 failed)
* Is it simple to track task status (`complete`/`fail`) within a workflow?
* Is it simple to assign a unique ID to each workflow execution? This is useful e.g. to place all logs or other aux files in a specific folder (ref https://github.com/fractal-analytics-platform/fractal-server/issues/134).

**Comment by jacopo-exact** [comment]
closed in 5b71268
