### ISSUE TITLE
Data lifecycle: Workflow Flexibility

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#14]
@gusqgm and I need to discuss the data life cycle for both labs and come up with clear user stories. Just placing this here as a placeholder and a place where we put down results of that discussion.

**Comment by tcompa** [comment]
A few comments, as of today's meeting:

> DLC6. As a user, I can perform e.g. statistical analysis on the extracted features and combine the extracted values together with the image data for e.g. Figure creation /presentations/science sharing.
> DLC7. As a user, I am responsible for keeping the compressed microscope raw data on the server until it is taped. Taping must follow local institution/group policies

These are not something to be concerned about right now. Yes, we'll need to port the compression task to the new architecture, but the rest will be discussed at a later point (and could depend a lot on the local policy).

> WF6. Each .zarr output history is directly associated with its presence on disk, i.e. if a .zarr output is deleted, so is its history.

fractal is not a file server, this is probably something we should not consider.

_Re checkpointing:_
Having a fully automated checkpointing of tasks is not the way to go for how fractal is being built (my take). The reason is that the abstraction of datasets (which are more than just file paths) lets us restart a workflow from the partial output of another one in a quite natural way (just setting the "right" input dataset).
What we agree on is that we should make it as smooth as possible for users to restart a workflow from a certain point (ref #107), and eventually to export/import a workflow which ran in this way.

_Re: history/pipeline files (several WF points)_
* Let's start to implement a simple history file, which gets written within each dataset #108. We'll then discuss about what precisely should go in there.
* Issue for import/export of fractal workflows: #1.

_Re: trying out a workflow on a subset of data_
* #109

**Comment by jluethi** [comment]
Our workflows have different parts (see also graphics above). This may not be a hard limit (e.g. we could construct workflows that don't follow this logic), but it may be useful to list typical workflow patterns to have a reference:

1. Preprocessing (image to image transformations)
2. Registration (only for multiplexing experiments)
3. Image Analysis (image to labels/tables)
