### ISSUE TITLE
Future feature wish: Import/export image list

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#1402]
It would be nice to add a feature to export & import an image list. The use cases I'm thinking about:

1. A user moved the Zarr to a different folder, now the dataset is "corrupted", e.g. will look for images where they aren't anymore
2. A user wants to process an existing Zarr, but the Import task doesn't pick up all the necessary types yet (e.g. illum_corr isn't saved in the Zarr => not created during import)

There will likely be more edge cases like this. Having a good way to export an existing image list, modify it and import it in a new dataset would be a good workaround for that

**Comment by tcompa** [comment]
Would it work if we implement this feature directly for a dataset, rather than for the image list? Or is it more relevant to import an image list into an existing dataset?

Regardless of the dataset vs image-list choice:
1. As compared to the workflow import/export feature, this one would be much simpler as it would not need to check/create any DB relationship, nor it needs to rely on unique identifiers (that is, task source).
2. The export feature is trivial, since it just boils down to calling the appropriate GET endpoint. We would still duplicate this endpoint into a `GET /api/v2/project/{project_id}/dataset/{dataset_id}/export/`, if working with datasets, to only include `name`, `zarr_dir`, `images` and `filters`.
3. The import feature is fairly easy to implement. I would stick with doing it backend-side (to be more uniform), and it would be a new endpoint (`POST /api/v2/project/{project_id}/dataset/import/`) which receives a dataset (`name`, `zarr_dir`, `images` and `filters`) and adds it to the DB.

**Comment by tcompa** [comment]
> Would it work if we implement this feature directly for a dataset, rather than for the image list? Or is it more relevant to import an image list into an existing dataset?

There's one more reason for working with the dataset rather than the image list.

Working with the image list:

1. I rename a certain folder on-disk, and then my dataset metadata are invalid
2. I export **the image-list** to a JSON file
3. I modify the JSON file, to fix the image zarr urls
4. I import the image list from the JSON file, but the zarr_dir is the same as before -> this leads to an error because zarr URLs must be relative to zarr_dir

Working with the dataset:
1. I rename a certain folder on-disk, and then my dataset metadata are invalid
2. I export **the dataset** to a JSON file
3. I modify the JSON file, to fix the image zarr urls **and the zarr_dir**
4. I import the dataset from the JSON file, and the urls are relative to the zarr_dir -> OK

**Comment by jluethi** [comment]
I see benefits either way. Dataset export/import also seems reasonable.

Potential image-list only import/exports would have the following benefits:
1. Simpler json structure for someone to modify (one less layer of keys)
2. Could more easily add ti an existing dataset, e.g. to keep the history of the dataset and “just” bulk-edit some entries or such

———

neither of those would be critical to have, so I’m fine if we implement it for the dataset for the time being

**Comment by tcompa** [comment]
> Simpler json structure for someone to modify (one less layer of keys)

Agreed.

> Could more easily add ti an existing dataset, e.g. to keep the history of the dataset and “just” bulk-edit some entries or such

Would this actually work?

* If we decide to first modify the dataset zarr_dir and then its image list, the PATCH-dataset API call fails because the dataset already contains images (ref #1385)
* If we decide to first modify the images URLs and then the zarr_dir, the import-image-list API call fails because the new image URLs are not relative to zarr_dir (ref #1319)

If we add the possibility of skipping one of these checks (e.g. via a query parameter `skip_relative_urls=true` for the import-image-list endpoint), we introduce the risk of remaining in an invalid state. The solution would be that the import-image-list endpoint could automatically update the zarr_dir, but then this looks very similar to an import-dataset endpoint (just with some hidden behavior).
