### ISSUE TITLE
refactor dummy tasks

### ISSUE THREAD

**Issue by jacopo-exact** [fractal-analytics-platform/fractal-server#167]
dummy tasks are currently split into multiple modules with lots of duplicate code

**Comment by tcompa** [comment]
We still need each one of the four task to be executable, and their `if __name__ == "__main__"` blocks do look slightly different (minor differences in the arguments, but most importantly that block should call the right function).

* What is very simple to do (and I am doing it right now) is to merge the pairs (`dummy`, `dummy_fail`) and (`dummy_parallel`, `dummy_parallel_fail`) - by adding a flag `raise_error=True/False`.
* What is less obvious (and I don't see a clear advantage in doing it - for such small testing tasks) is to merge `dummy` and `dummy_parallel`, since they have a different call signature (one takes `component`, the other one does not).
