### ISSUE TITLE
Allow Fractal to be able to send jobs to different slurm clusters within a federation

### ISSUE THREAD

**Issue by gusqgm** [fractal-analytics-platform/fractal-server#169]
From the resource infrastructure point of view, running things with the current Drogon architecture means making luigi send jobs to either a dedicated CPU VM or to a physical workstation that has a Quadro RTX 8000 for processing segmentation with pre-trained neural networks.From the resource infrastructure point of view, running things with the current Drogon architecture means making luigi send jobs to either a dedicated CPU VM or to a physical workstation that has a Quadro RTX 8000 for processing segmentation with pre-trained neural networks.

From the perspective of the lab, it would be useful to expand our minislurm cluster in order to add the gpu workstation to it as a new node so we could run with the same resource capacity as Drogon currently.

One logical step is then to make the large FMI cluster and our minislurm part of the same federation, so that jobs can be sent either to our local or to the institute wide slurm depending on some basic parameters (e.g. queue size, resource demands, etc).

I have been checking the [slurm documentation](https://slurm.schedmd.com/federation.html) and the [slurm.conf docs](https://slurm.schedmd.com/slurm.conf.html#index) it looks like creating a federation of clusters should conceptually not be so difficult as long as ideally all of the related clusters run the same version of slurm (which will be our case very soon as we are currently updating the clusters). Each cluster keeps its own database. Creation of a federaion is done with the `sacctmgr ` command and in practice Fractal would need to add a `-M,--clusters=<cluster_list>` and the `--cluster-constraint=[!]<constraint_list>` options. 

This would be very useful for us, as we would then have the flexibility to run Fractal within our own slurm resources or be able to outsorce larger jobs to the large cluster without the need of having two independent Fractal installations. 

I do see however that this can be thought right now as a rather more specific implementation case, so here is the important question: How much work would this mean for the fractal-server? Is there anything in the current architecture that would prevent us from having this road available?

**Comment by tcompa** [comment]
Are those options (`-M,--clusters=<cluster_list>` and `--cluster-constraint=[!]<constraint_list>`) related to `sbatch` or to `sacctmgr`?

Briefly: whatever you can do with a `sbatch` script should be "easily" doable within fractal:
* In the current version, the `sbatch` script is generated by parsl, which lets you add any additional configuration (see parameters `scheduler_options` in [SlurmProvider](https://parsl.readthedocs.io/en/stable/stubs/parsl.providers.SlurmProvider.html)).
* In a possible future version of fractal-server, where we could use a simpler SLURM interface, it is reasonable that we'll always be able to provide additional sbatch parameters.

Some other questions:
1. Do the two different clusters share a filesystem? At least in the current version, this is strictly needed.
2. Do the two different clusters share users? Otherwise we will need to associate one fractal user to two cluster users (one per cluster)

**Comment by jluethi** [comment]
We already discussed this in calls, but for completeness:

Those should be sbatch options, right?

> 1. Do the two different clusters share a filesystem? At least in the current version, this is strictly needed.

Yes they do

> 2. Do the two different clusters share users? Otherwise we will need to associate one fractal user to two cluster users (one per cluster)

Share users as in usernames or credentials? The setup would be done in a way that the users have the same name on both clusters. And the fractal user on both should have sudo rights to impersonate them. So I think that should be fine as well.

**Comment by tcompa** [comment]
> Share users as in usernames or credentials? The setup would be done in a way that the users have the same name on both clusters. And the fractal user on both should have sudo rights to impersonate them. So I think that should be fine as well.

Warning: this is not what I understood from the call with @gusqgm.
*  My understanding was that the "Joel" users of the two clusters in the federation are the same one, and not two different ones with the same name. This point is not blocking, but let's clarify it.
* More importantly, we are **not** planning to have multiple fractal instances, one running on each cluster of the federation. Rather, we have a single fractal server running, from a place where the user would be able to submit a job to the federation (and then it's SLURM that selects the appropriate cluster to use). In this situation, there is no "fractal user on both", since each human user at FMI is only associated to a single fractal user.

**Comment by jluethi** [comment]
My bad. @gusqgm Can you confirm? Probably me having misunderstood the discussion on Wednesday!

**Comment by gusqgm** [comment]
So, to clarify some points:

The utilization of a federation means that we have fractal server running somewhere in the common storage, and this single instance will be able to communicate to any member of a federation, since with the `-M` command it is possible to choose which cluster of the federation should execute the job. There is the possibility that fractal itself knows to which cluster of the federation the job should be sent, as well as the scenario where slurm should be able to select the cluster based on specific parameters of the job in question.

From my current understanding of this approach, I do agree with what @tcompa wrote above is correct: there should be just one user that fractal should be able to impersonate.

Once we start trying this here I will be able to give more information. 👍

**Comment by jluethi** [comment]
After long discussions at FMI, we're not currently continuing the federation approach, but aim for just running on the main cluster. Thus, we can close this issue for the time being.
