### ISSUE TITLE
New import feature not matching tasks correctly

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#1938]
Not sure if this is backend or front-end

I briefly tested the new export/import feature. The export looks reasonable. But reimporting the workflow makes all tasks the last task of the workflow in my case.

This is how it looked originally:
<img width="1412" alt="Screenshot 2024-10-21 at 09 38 13" src="https://github.com/user-attachments/assets/ecb4df7c-e97b-4d69-9e68-147c068008fd">

Here is after the export & re-import:
<img width="1412" alt="Screenshot 2024-10-21 at 09 38 09" src="https://github.com/user-attachments/assets/275240b8-31e2-4ee9-b4af-0014c424418f">

The parameters for the third task are fine. The others look unset on Fractal web.

Here's the workflow I tried to import

[workflow-export-Demo-1729496167023.json](https://github.com/user-attachments/files/17456882/workflow-export-Demo-1729496167023.json)

If I export that workflow again, I get the correct workflow that shows all the correct parameters, but the task names are wrong.
[workflow-export-Demo Test-1729496351367.json](https://github.com/user-attachments/files/17456937/workflow-export-Demo.Test-1729496351367.json)

------

I see 2 things that go wrong:
1. The matching of the tasks appears to go wrong on import
2. Somehow, tasks keep all their paramters set, even if that task type doesn't even have those parameters.

**Comment by tcompa** [comment]
Thanks for testing!

> The matching of the tasks appears to go wrong on import

This is clearly a bug - which is being fixed in #1939.

> Somehow, tasks keep all their paramters set, even if that task type doesn't even have those parameters.

If I understand correctly what you mean, this is expected.
The fact that task arguments comply with a given JSON schema is only verified client-side. In what happened above, the backend is setting the task arguments correctly, but getting the wrong task ID - but the backend won't verify that the task arguments of the first task (which is meant to be a converter task) match with the task type (which turns out to be, by mistake, a cellpose task).

Another question may be: why is the webclient not throwing an error? I would expect that if you click on the first task in the list (after the "wrong" import-worfklow operation) you won't be able to interact smoothly with fractal-web? Or, if you do, it means that all "extra" arguments are simply ignored when validating data against their JSON schema.
