### ISSUE TITLE
Setting a task-specific (python) environment

### ISSUE THREAD

**Issue by jacopo-exact** [fractal-analytics-platform/fractal-server#2]
EDIT
This issue now concerns how to best setup a set of task-specific environments.
Making the server independent on the task package is now a consequence of https://github.com/fractal-analytics-platform/fractal-server/issues/132 (together with the new situation where tasks are run only by the users, and never by the `fractal` user).

~~particularly important for testing the client without installing too many subdependencies.
add a config parameter to set which packages to search for task manifests~~

**Comment by jluethi** [comment]
This flexibility & modularity sounds great! Full support that we're going that way!

3 questions that come up: 
a) When does the user need to specify the task package? Just upon project creation? Or is 3 also meaning e.g. during task apply (that wouldn't make that much sense to me). Having this as something during project creation sounds very reasonable
b) For future flexibility, would be great if 1) multiple tasks packages can be registered [e.g. our users will always need fractal-tasks-core, but sometimes additional packages on top] and 2) if that can be modified after a project has been created
c) How exactly will we specify task packages? By name that is pip installable (but then we should also include a version possibility)? Or name with a github link? Or path to something that is installed on the server? We can start simple of course and make it broader later :)

**Comment by tcompa** [comment]
> a) When does the user need to specify the task package? Just upon project creation? Or is 3 also meaning e.g. during task apply (that wouldn't make that much sense to me). Having this as something during project creation sounds very reasonable

I would say that this happens at the project creation level (probably unclear in my previous comment).

> b) For future flexibility, would be great if 1) multiple tasks packages can be registered [e.g. our users will always need fractal-tasks-core, but sometimes additional packages on top] and 2) if that can be modified after a project has been created

Multiple packages are already considered (provided that they have a fractal-compatible manifest).
And task collection is an independent function (already in the current version), which in principle can be called as many times as needed.

> c) How exactly will we specify task packages? By name that is pip installable (but then we should also include a version possibility)? Or name with a github link? Or path to something that is installed on the server? We can start simple of course and make it broader later :)

This is the most relevant question, and still to be discussed further (among us, and then together on Wednesday).
Meanwhile, what is coming out of #112 (and which ex-post becomes a bit obvious) is that user must take care of installing relevant packages in their home environments. Say a user wants to use `fractal-tasks-core` and also a very specific version of an external library (which they wrapped into a task module `my-tasks`), then within this scheme they would have to:
1. `conda create a-very-specific-env`
2. `pip install fractal-server fractal-client fractal-tasks-core` 
3. Install `my-tasks`. It doesn't matter how they set it up (from github, from local path, from pypi..), but they should be able to do `from my_tasks import a_certain_task`. In this step, they also select whatever version they prefer of all dependencies (at the moment this wouldn't be 100% flexible, since they still need to install fractal components with their version constraints, but that's not a terribly heavy amount of dependencies/constraints).
4. Communicate to `fractal-server` the string MODULE such that `from MODULE import a_certain_task` works (where MODULE could be, for instance, the string `fractal_tasks_core` or `my_tasks`).

As soon as we move to the submit-as-a-user approach, the `fractal` cannot install anything in the user homes/environments, and this responsibility is transferred to the user (including picking the right versions for dependencies). Of course our job would be to make things as clearly documented as possible (and probably we should log some properties of the user's environment within fractal), but that doesn't change the core message: if a task is run by a user, the relevant env is the user's one. To make it even higher level: fractal server/client components would be completely agnostic to whatever env/tasks the user chooses (provided that tasks have a manifest), while `fractal-tasks-core` would be _just_ one of the many possible task packages.

**Comment by jluethi** [comment]
Sounds good to me as a direction! I'd suggest we have a default env around for the fractal-tasks-core that users can use, or they can provide their own, custom one :)

**Comment by jluethi** [comment]
Following up on the discussion today on this: A project-specific environment is certainly a good first step. We will need task-specific environments though. 

I've been thinking about this a bit more. A great default would be:
1) Each task takes an environment that can be set as an input argument
2) There is a default environment for all the core tasks
3) That default environment can be set with an environment variable on the server side, e.g. `$FRACTAL_CORE_ENV` being set to the path to that environment

Thus, once we have this added, if things are set up correctly, a starting user can ignore the whole environments and core tasks typically should run fine in the default as long as it's set up properly. 

----
Why task-specific environments? I think there are 3 main use-cases for custom or specific environments:
i) Developing new tasks: this should not mess with how the old tasks run
ii) Running neural network tasks: They may require e.g. different tensorflow versions for different networks. And a user may want to run 2 different networks in the same workflow
iii) Running napari workflows: Depending on the napari workflow a user may want to run, this may require different dependencies and those may have conflicts. Again, a user may want to run multiple workflows and we don't want to handle those conflicts.

Plus, small addendum: There is a discussion on the napari workflows side about whether the workflows would directly come with an environment. That again would be specific for that workflow task then

**Comment by tcompa** [comment]
In the new architecture, closing https://github.com/fractal-analytics-platform/fractal-server/issues/132 replaces the original purpose of this issue (making the server independent on the tasks packages).
Let's reorient this issue towards "Setting a task-specific (python) environment"

**Comment by jacopo-exact** [comment]
closed in #198
