### ISSUE TITLE
Is `pip show` output reliable? Can we make it standard?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#201]
This came up during https://github.com/fractal-analytics-platform/fractal-server/pull/198

**Comment by jacopo-exact** [comment]
is this still an issue? I removed the `-f` flag in `pip show` as it is not necessary in be55347

**Comment by tcompa** [comment]
I was rather thinking about a machine-readable output for `pip show` command, but it looks like previous PRs in that direction were closed and the current output is considered to be machine-readable:
* https://github.com/pypa/pip/issues/5261
* https://github.com/pypa/pip/pull/5514

However `pip list` does have a `--json` flag. This is not high-priority, but I propose we use `pip list --json > /some/tmp/file.json`, and then
```python
# load /some/tmp/file.json
location = next(package for package in package_list if package["name"] == "devtools")["location"]
```

**Comment by jacopo-exact** [comment]
didn't know about this. moving this issue to the backlog milestone

**Comment by jacopo-exact** [comment]
to address this issue, see

https://github.com/fractal-analytics-platform/fractal-server/blob/main/fractal_server/tasks/collection.py#L389

**Comment by jacopo-exact** [comment]
seeing a bit more in detail the output of `pip`, I think it is better to keep the parsing of `pip show [pkg]` rather than moving to `pip list --json` and then parsing the output.

However I do think that it is better to make package installation path discovery more robust by re-activating the `-f` option and using its output to extract the base path. The final `package_root` should be the value of location as it is now path-concatenated with the base path of the output of `-f`, e.g.,

```python
stdout_inspect_lines = stdout_inspect.split("\n")
location = Path(
        next(
            line.split()[-1]
            for line in stdout_inspect_lines
            if line.startswith("Location:")
        )
    )
package_name = Path(stdout_inspect_lines[-1]).parts[0]
package_root = location / package_name
```

**Comment by jluethi** [comment]
-f option seems to be good enough for us atm
