### ISSUE TITLE
CI / docker improvements

### ISSUE THREAD

**Issue by jacopo-exact** [fractal-analytics-platform/fractal-server#333]
Right now we use `pytest-docker` to start ancillary containers for testing, namely a slurm-cluster-in-docker to submit jobs to.

Currently the fixtures
1. tar the server code
2. pre-install hardcoded server dependencies to create a cached layer
3. build the docker images, installing the dev version of the server
4. start the containers
5. typically do not cleanup the containers if the test suite is keyboard interrupted.

We should
- [ ] only create a new tar if there were changes with respect to the last run
- [x] avoid hardcoding the dependencies, possibly by automating a call to `poetry export --without-hashes -E slurm` and caching its hash, so that we rebuild the layer only when needed.
- [ ] find a way for docker to exit gracefully

**Comment by tcompa** [comment]
Cache of the environment can be obtained as in https://github.com/fractal-analytics-platform/fractal-tasks-core/blob/main/.github/workflows/ci.yml

**Comment by tcompa** [comment]
Concerning the hardcoded `requirements.txt`, there doesn't seem to be any relevant speedup in having this cached layer.  See for instance:
* https://github.com/fractal-analytics-platform/fractal-server/actions/runs/3795129574
* https://github.com/fractal-analytics-platform/fractal-server/actions/runs/3794999005

Let's just remove this feature, since it also means a higher complexity - see #389.

**Comment by tcompa** [comment]
Re: "only creating a new tar if something changed", this does not appear as a way to significantly reduce runtimes.

Re: "proper cleanup", this is in principle already implemented.

Closing for now.
