### ISSUE TITLE
Add additional options to sbatch submission: `-A` for accounts

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#491]
One thing we discovered during tests at FMI today: We currently don't specify the account name with the `-A` option. On the FMI clusters, those accounts (different from the slurm-username. More like "what group does that user belong to) are being used actively. e.g. my user belongs to the `fractal` account.

So far, our users had default accounts and those worked well. I still think that will probably be a reasonable setup for many locations. But would be useful to add support to add an account option during user registration and optionally use this during slurm SBATCH submissions.

**Comment by tcompa** [comment]
Sure, we can include a line like
```
#SBATCH --account=<account_name>       # account name
```
in the sbatch script.

---

> and optionally use this during slurm SBATCH submissions.

Does "optionally" mean "if the user has an account set, then always use it for their submissions" or does it mean "use it, but not always"?
* If it's something that is strictly fixed, for a user, then we should add it to the database (typically upon user registration) and whenever it is present it will be used for submissions. Note that users would not be able to update it themselves, since user edits are restricted to the admin.
* If it's something that the user may want  to change over time for whatever reason (as in "project A should count on account B, but project C belongs to account D"), then we should rather add it as an option to workflow-submission (*).


(*) I think that adding the SBATCH line above to `worker_init` would probably already work in the current version, but if it's an intended use then we should have it as an explicit additional argument.

**Comment by jluethi** [comment]
> Does "optionally" mean "if the user has an account set, then always use it for their submissions" or does it mean "use it, but not always"?

Optionally as in, if it's present, set this option. But if it's not, set nothing (i.e. don't enforce that it needs to be present, because we don't use this e.g. in the Pelkmans lab).

Interesting question regarding how constant this is. We didn't use those at UZH, but they are in use at FMI. Can you comment on how they are used @gusqgm ?
My understanding would have been: This should be strictly fixed (minus a very rare chance that the cluster setup gets changed). I think it would fit well as an optional registration parameter. A user should need to think about this.
But I don't know whether they are used in different ways at FMI.

Also, interesting point about worker_init :)

**Comment by jluethi** [comment]
I tried the `worker_init` approach and happy to confirm that this works :)
Setting `#SBATCH -A fractal` in `worker_init` gets us running for the users that had previously gotten a `ERROR:slurm_runner:sbatch: error: Batch job submission failed: Invalid account or account/partition combination specified`

Let's still talk about how we best pass this option long term. But not an urgent thing to add, given that we have a way the user can set it via `worker_init`.

And if it's actually something that will change depending on projects or such, then the worker_init may already be the way to do it :)

**Comment by tcompa** [comment]
`account` is now part of the most recent SLURM-backend configuration in fractal-server 1.2.0, see https://fractal-analytics-platform.github.io/fractal-server/reference/fractal_server/app/runner/_slurm/_slurm_config.

Let's re-open (here or elsewhere) if it doesn't work as expected.

**Comment by jluethi** [comment]
I can confirm that the account settings are working correctly at FMI with the configuration in the slurm config.
