### ISSUE TITLE
Define strategy for grouping tasks into slurm submissions

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#493]
As discussed at the call today, we should discuss a strategy for running larger experiments at the FMI.

The main limits are:
1) Max. 100 jobs at once (we can limit this, see here: https://github.com/fractal-analytics-platform/fractal-server/issues/377)
2) Max. 200 jobs per hour

The < 200 jobs per hour is not something we can easily achieve for processing e.g. 384 well plates in the current runner. We started some discussions on combining multiple srun statements (one per task that needs to be run for a given well) into a single sbatch submission. Let's explore how well this would fit into our current runner framework and what downsides we will hit with it.

I expect the logging and knowing which well failed (if only 1 fails) to be trickier. Also question of whether that can still be generated through clusterfutures or we need to adapt things here.

Also, if we go that way, we should make the combining of jobs flexible. As came up during the call: It may be a good idea to group e.g. 20-40 tasks (tasks applied to a single well) into one sbatch submission for many of our core tasks like the parsing from yokogawa to OME-Zarr, illumination correction or max. intensity projection. It may make less sense for the cellpose tasks (depending a bit on settings) to combine as many tasks in a single slurm job (as our nodes have 1-4 GPUs, so couldn't run that many jobs in parallel in any setting).

Scope limit: We are not considering setup to combine sequential tasks run on the same well in a single slurm job.

**Comment by tcompa** [comment]
Some sparse notes from our discussion this morning:

* The most relevant use of this feature would be to have many fractal parallel tasks (let's say their number is `BATCH_SIZE`, and let's say that this could be in the 10-20 range) running in parallel inside a single SLURM job.
* The number of SLURM required tasks (let's call it `NUM_SLURM_TASKS` for the moment) would determine the degree of parallelism. In principle `NUM_SLURM_TASKS` could be as large as `BATCH_SIZE`, but we may want to have it a bit smaller to avoid requesting a large amount of resources.
* Setting `NUM_SLURM_TASKS=1` would mean that the `BATCH_SIZE` tasks of a single SLURM script are executed one after the other, sequentially.
* `NUM_SLURM_TASKS=1` is likely what we'll do for tasks that require a gpu (or at least this will be the first approach to those tasks, before further exploration of whether we can run many of them in parallel).
* In most other cases, we'll set `NUM_SLURM_TASKS` to a larger value. As soon as this variable is larger than 1, all resource-allocation requests in the SLURM script need to be scaled up. This means that we have a knowledge of which SLURM parameters need to be scaled (typically `cpu` and `mem`, but possibly others?). Notice that this won't play well with SLURM options that are defined in `extra_lines`, as fractal-server cannot handle them automatically.


**Very preliminary** list of changes/decisions:
* For each parallel task, we need to know the value of `NUM_SLURM_TASKS` (which depends on the task) and `BATCH_SIZE` (which may be a global server configuration, in principle, or otherwise should be also set on a per-task level).
* The `FractalSlurmExecutor.map()` method need to be rewritten, because it cannot any more consist in a repeated call to `FractalSlurmExecutor.submit()`. Rather it should call a single `submit` (is it the same as `FractalSlurmExecutor.submit()` or a custom method? To be checked), which prepares a sbatch script with multiple `srun` statements and with the appropriate SLURM options.
* We need to write a new version monitoring which is currently in-place in (our version of) clusterfutures, to see whether jobs are complete and catch errors. We can still use the part that checks whether a certain jobid is present in squeue, but the existence checks of a single output pickle file need to be modified - and the same goes for checking that the pickled output corresponds to a successful end of a task.
Note that the old version should remain there, since it is used for the non-parallel tasks.
* Also the error handling should be split into the two cases (parallel or non-parallel tasks), and we should try to make errors reasonably informative in case a certain task of certain task batch fails.

Side comment: due to the several complexities introduced by this plan, we should reconsider whether it is still worth supporting the [FRACTAL_RUNNER_MAX_TASKS_PER_WORKFLOW](https://fractal-analytics-platform.github.io/fractal-server/configuration/#fractal_server.config.Settings.FRACTAL_RUNNER_MAX_TASKS_PER_WORKFLOW) variable (and the corresponding functionality). I clearly understand that its use goes beyond the SLURM backend (we noticed that it can also be useful to reduce memory usage when running things locally), but let's re-discuss a bit later about how it fits in with this new (proposed) scheme.

**Comment by jluethi** [comment]
Thanks for the overview @tcompa !

I'm not 100% sure about the details of how to do this in slurm. But I wonder whether a lot of the resource specification can get easier if we use SLURM's "per task" resource specification. For example, the -c, --cpus-per-task option controls CPUs per task. Can we also use the -n, --ntasks option to control how many tasks run at once?
And maybe via `--mem-per-cpu` to get to memory that then scales up?

Would that be the slrum way to do what we want here, while we just submit our `BATCH_SIZE` jobs via srun? Do you know whether the `--ntasks` option is actually doing the thing described as `NUM_SLURM_TASKS`?


Regarding  `FRACTAL_RUNNER_MAX_TASKS_PER_WORKFLOW`: Nice if we can keep it to enforce that limit and to make it easier to run some local tests. But if it gets complicated, I'd rather we implement the job batching well and see later how big the need for max tasks options are (or whether they become something specific to the local runner)

**Comment by tcompa** [comment]
> I'm not 100% sure about the details of how to do this in slurm. But I wonder whether a lot of the resource specification can get easier if we use SLURM's "per task" resource specification. For example, the -c, --cpus-per-task option controls CPUs per task. Can we also use the -n, --ntasks option to control how many tasks run at once? And maybe via `--mem-per-cpu` to get to memory that then scales up?

Tests are underway (refs https://hpc.nmsu.edu/onboarding/supercomputing/slurm/running-series-parallel/, https://hpc.nmsu.edu/discovery/slurm/serial-parallel-jobs/, https://portal.supercomputing.wales/index.php/index/slurm/interactive-use-job-arrays/batch-submission-of-serial-jobs-for-parallel-execution/, https://stackoverflow.com/questions/39186698/what-does-the-ntasks-or-n-tasks-does-in-slurm).

> Do you know whether the `--ntasks` option is actually doing the thing described as `NUM_SLURM_TASKS`?

They are related, but not the same. That is, we can have a case where `--ntasks=1` allows multiple execution at once.

More on this later.
