### ISSUE TITLE
Project directory creation & user-specific base-path for project directories?

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#553]
See https://github.com/fractal-analytics-platform/fractal-web/issues/48 for motivation

> On the CLI side, we create the project dir before we create a project as well and I assume that's why the project creation endpoint requires an existing directory. We should think about whether the directory can also be created at that moment (not trivial, as it needs to be a user action when the user and server aren't the same).
> Also, we should think whether there would be some default base directory where project directories are created, such that the user does not need to specify anything about this directory by default. I'll open a corresponding fractal-server issue.

**Comment by jluethi** [comment]
I've also seen that multiple project can share the same project directory. Given their main usage (a place to put the `workflow_000001_job_000001` folders): Do we actually need different project folders? It makes it a bit easier to see which project a workflow belongs to. But the `workflow_000001_job_000001` will always be unique (until the server is restarted).

Given that we'll likely still restart the server from time to time, having unique project folders can be useful to avoid having to do cleanup. But already when we'd start auto-creating project directories, the question of when they get cleaned up and what happens when there is a conflict with an existing project directory becomes important.

**Comment by tcompa** [comment]
Agreed, there is a bit of confusion here.

Some general comments first
1. I'd rather keep the use of `sudo` confined in the runner component, without relying on it e.g. in the new-project endpoint. This seems logically consistent: creating a project should not require fractal-server to handle anything which is in user-owned directories (note that it currently does -see #555- but that is to be fixed).
2. The project directory is not being used as its name would suggest, but rather as a temporary folder to store files which are then copied over into fractal-server internal folders (which constitute the only reliable source for the corresponding information). This should rather be called "cache" folder, or something similar.
3. The project directory is not really related to a project, but it's a container for all job subfolders. There is no real reason to have one such folder per project, because:
    * The logical separation would be easily achieved by adding the project id in the subfolder name.
    * We do not expect the user to ever go into those job folders, unless they know about their existence and need some quick debugging info. This also means that it's not a problem if the name is very complex/verbose (see example below).

One possible implementation:
* Upon user registration, we also define a "cache" folder for each user (the "cache" name can be replaced with more appropriate ones). The folder may be user-owned and with restricted access. Fractal-server only checks that this attribute is an absolute path, but nothing else (thus avoiding #555).
* We drop the `project.project_dir` attribute.
* When submitting a workflow for execution, **inside the runner component**, we handle the server-side and user-side job folders. The server-side one is trivial to handle. For the user-side one:
    - We create the cache folder (if missing), making use of `sudo mkdir`.
    - We create the job folder, with a name like `{timestamp}_project_00012_workflow_123123_job_123123`. The timestamp is useful because if you reset the DB you may end up with two repeated folder names. I'd rather avoid calling `sudo rm` on user's folders - in my view this should be a user's task.
* To be decided: how/when is this cache removed/compressed, and by whom? See also https://github.com/fractal-analytics-platform/fractal-server/issues/474.

**Comment by jluethi** [comment]
I like this suggested approach! :) Nice workaround with the time stamp to keep testing easy as well!
