### ISSUE TITLE
New SLURM-configuration logic (where? in config files or in submission-script preparation?)

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#576]
Right now, a SLURM configuration file for FRACTAL may look like the one below, where we list a few pre-made "operation modes" ("cpu-low", "cpu-mid", "gpu", ...) and define the corresponding SLURM options for each one of them. These options are meant to be used in a single-task SLURM job, which guarantees that (if we choose them carefully the first time) we won't hit any error like "it's impossible to allocate the required resources". If, for instance, the maximum memory per node is 62G, then all of the operation modes listed below will eventually fit in in one of the nodes.

```JSON
{
    "cpu-low": {
        "partition": "main",
        "mem": "7g",
        "cpus-per-task": "1"
    },
    "cpu-mid": {
        "partition": "main",
        "mem": "15g",
        "cpus-per-task": "4"
    },
    "cpu-high": {
        "partition": "main",
        "mem": "61g",
        "nodes": "1",
        "cpus-per-task": "16"
    },
    "gpu": {
        "partition": "gpu",
        "mem": "61g"
    }
}
```

This assumption breaks with #572, since a single SLURM job may now be made of multiple Fractal tasks to be run in parallel.
For instance if we include a memory-heavy Fractal task as `cpu-high`, but then try to combine two such Fractal tasks in the same job to be run in parallel, then SLURM won't ever schedule this job because there is no node with 61*2=122 memory that can be allocated.

---

This means that #572 adds one more failure modes, which boils down to "the user chose a value of `n_parallel_ftasks_per_script` which collides with the available resources". At a difference with the current configuration, the value of `n_parallel_ftasks_per_script` is a global variable that is set for the whole fractal-server instance (or at least that's my guess), but rather something which changes dynamically. For this reason the check need to be repeated for each Fractal-task execution.

Questions:
1. How flexible do we expect the setting of `n_parallel_ftasks_per_script` to be? See #577.
2. How could we prevent or handle the failure mode mentioned above?
 
One possible solution is to add one more field to the configuration file entries, called for instance `"maximum_parallelism"`. For the example above, we would set it as follows:
```
Operation mode, maximum_parallelism
cpu-low         8
cpu-mid         4
cpu-high        1
gpu             1
```
and then we would fail any time a user tries to combine more than `maximum_parallelism` Fractal tasks to run simultaneously as part of a single SLURM job.

**Comment by tcompa** [comment]
Side note about:
> Questions:
> 1. How flexible do we expect the setting of `n_parallel_ftasks_per_script` to be? See #577.
> 2. How could we prevent or handle the failure mode mentioned above?

A single decision may answer both questions, for instance if we decide that `n_parallel_ftasks_per_script` becomes part of the specification of a given operation mode, as in
```JSON
{
    "cpu-low": {
        "partition": "main",
        "mem": "7g",
        "cpus-per-task": "1"
        "n_parallel_ftasks_per_script": "8"
    },
...
}
```

**Comment by jluethi** [comment]
Very good discussion!

> the value of n_parallel_ftasks_per_script is a global variable that is set for the whole fractal-server instance (or at least that's my guess), but rather something which changes dynamically.

I would also assume that this can vary by task.

In general, we started with Executors to have an easier setup and because Parsl is thinking in executors. I don't think we need to always think in executors necessarily, at least not as something that's exposed to the user.

I'll put down some thought on what we'd want to achieve and we can then discuss whether the executor setup is how we want to do this or if there's another approach we'd want to take.

----

Each Fractal setup will run on a given infrastructure with defined node-sizes. The user shouldn't need to worry about those.

Each Fractal task will require a certain amount of CPU, memory, GPU and potentially runtime. We should have good defaults, but make it possible for the users to adapt here. Users may need to adapt these "per task" parameters sometimes.

Other important parameters are `n_ftasks_per_script` and `n_parallel_ftasks_per_script`. The `n_ftasks_per_script` is mostly defined by the architecture Fractal is running on (i.e. rules on max job numbers at FMI, trade-offs of how fast slurm jobs can be submitted at UZH etc.). Most users shouldn't have to change this parameter. It should mostly be the same for the whole deployment, with some optional overwrite by power users?

`n_parallel_ftasks_per_script` is something that needs to vary by tasks (e.g. GPU tasks will always be 1 - low, CPU tasks may be something like 4-96, depending on the setup). I would again imagine reasonable defaults being set for the specific Fractal instance, but some way for the user to overwrite them.

----

Based on those parameters, how do we design the slurm jobs & their requirements?

Do we have preset executors and just fit it in the "smallest" fitting executor?
i.e. if we need 17 GBs of RAM, do we start a slurm script with 17 GB of RAM requirement or the CPU-high executor with 61 GB of RAM?

How do we handle user input that would not work?
i.e. at UZH, max memory (for most nodes) is ~62 GB. What if a users wants to run `n_parallel_ftasks_per_script` = 4 and each task needs 60 GB of RAM?


Overall, we'll need to have some definition of "available nodes". Maybe via executors, maybe somehow else.
If a user changes `n_ftasks_per_script` into something sub-optimal, that's mostly a user issue (i.e. things may run slower if everything is in 1 job).
If a users sets `n_parallel_ftasks_per_script` + requirements that don't match, we could also consider `n_parallel_ftasks_per_script` as "maximum number of jobs that run in parallel", 
i.e. if a user requests `n_parallel_ftasks_per_script` = 4 and each task needs 60 GB of RAM, we run it with `n_parallel_ftasks_per_script`=1 on cpu-high
if a user requests `n_parallel_ftasks_per_script` = 4 and each task needs 30 GB of RAM, we run it with `n_parallel_ftasks_per_script`=2 on cpu-high

**Comment by jluethi** [comment]
> n_parallel_ftasks_per_script as "maximum number of jobs that run in parallel"

No.

**Comment by tcompa** [comment]
Here is a brief update on how different SLURM parameters are defined in the current version of #582 (e.g as of https://github.com/fractal-analytics-platform/fractal-server/pull/582/commits/9b48c47eb2936c2ae80c5780a55e23a3b08d965c). This mostly works, but it is obviously open to comments and requests for changes.

---

The goal of what I describe here is to fill in the values of the attributes in the `SlurmConfig` class below. For the record, this is done in the `set_slurm_config` function, so that what we are discussing here is exactly the implementation of this function.

```python
class SlurmConfig(BaseModel, extra=Extra.forbid):
    """
    Abstraction for SLURM parameters
    """

    # Required SLURM parameters (note that the integer attributes are those
    # that will need to scale up with the number of parallel tasks per job)
    partition: str
    cpus_per_task: int
    mem_per_task_MB: int

    # Optional SLURM parameters
    job_name: Optional[str] = None
    constraint: Optional[str] = None
    gres: Optional[str] = None
    time: Optional[str] = None  # FIXME: this will need to scale up with #tasks
    account: Optional[str] = None

    # Free-field attribute for extra lines to be added to the SLURM job
    # preamble
    extra_lines: Optional[List[str]] = Field(default_factory=list)

    # Metaparameters needed to combine multiple tasks in each SLURM job
    n_ftasks_per_script: Optional[int] = None            # If None, we will use some heuristic to set it
    n_parallel_ftasks_per_script: Optional[int] = None   # If None, we will use some heuristic to set it
    target_cpus_per_job: int
    max_cpus_per_job: int
    target_mem_per_job: int
    max_mem_per_job: int
    target_num_jobs: int
    max_num_jobs: int
```

Note that there is a list of SLURM options which is "natively" supported, while any "unexpected" option would need to enter the `extra_lines` attribute. Suggestions of other relevant options to include are welcome.

---

Briefly, the list of sources (starting with the highest-priority one) is:
1. `meta` attribute of a `WorkflowTask`
2. `meta` attribute of the `Task` associated to a `WorkflowTask`;
3. Variables coming from a site-specific Fractal SLURM configuration file.

The structure of items 1 and 2 is the same as for the arguments, where anything which is defined in the `WorkflowTask` overrides `Task` arguments. These two sources are used for all SLURM-option attributes (and for an additional `needs_gpu=True/False` flag), but not for the heuristic metaparameters.

The structure of item 3 and its relation with the attributes above require a more detailed explanation.

---

An example of a Fractal SLURM configuration file could be like
```python
{
  # Default SLURM options
  "partition": "main",
  "extra_lines": ["#SBATCH --some-option=some-value"]
  # GPU-specific SLURM options
  "if_needs_gpu": {
    "partition": "gpu",  # if different from the default one
    "gres": "gpu:1",
    "constraint": "gpuram32gb",
    "extra_lines": ["#SBATCH --some-gpu-option=some-gpu-value"]
  },
  # Options for task batching into multitask SLURM jobs
  "cpus_per_job": {"target": 8, "max": 16},
  "mem_per_job": {"target": 32000, "max": 62000},
  "number_of_jobs": {"target": 10, "max": 100}
}
```
This file includes three blocks:
* Default SLURM options represent the lowest-priority source. This block can accept any of the keys mentioned above (`cpus_per_task`, `mem`, `gres`, `account`, ...).
* The `if_needs_gpu` block includes a set of options that are appended to the default ones (and take priority, in case of overlap) whenever a WorkflowTask (or its corresponding Task) has `WorkflowTask.meta["needs_gpu"] = True`. This block is meant to host all options that are needed to run SLURM jobs on GPUs, in a specific cluster. Examples would be `{"partition": "gpu"}` or `{"gres": "gpu:1", "constraint": "gpuram32gb"}`.
* The three keys at the end (`cpus_per_job`, `mem_per_job` and `number_of_jobs`) are the metaparameters that enter the heuristics in #577, and once again they are specific to the cluster where fractal-server is running.

Note: the default/gpu blocks accept many SLURM options, and they could in principle be used as two cpu/gpu "executors" (defined as we did with the legacy SLURM backend), but this is not the usage I suggest. In my opinion, definition of memory/cpu requirements should rather be at the Task or WorkflowTask level, and the default/gpu blocks should only include very general options like the partition name or some gpu-specific option.

**Comment by jluethi** [comment]
Thanks for the great overview. Looks very nice to me! I'll have to test it to give finer feedback, but on the conceptual level, I don't see any issues with it.

Would also be flexible enough to e.g. have a default amount of memory & CPUs set per task, but we could provide template workflows for things that deviate a lot from normal expectations (=> just workflows to be imported), i.e. a 2D processing template that requests less RAM or a large 3D template that requests more :)
