### ISSUE TITLE
TaskExecutionError: pickle file is not deserialized when invalid executable given for task

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#644]
@adrtsc ran into an issue when trying to use a custom task: The task was registered wrong, such that the executable wasn't an actual executable (i.e. `/path/to/env function.py`, not `/path/to/env/bin/python function.py`.

The error then doesn't show up properly in the on-disk logs, but is displayed in the `fractal job show`. And the pickle files contain the error message, though somewhat hard to read.

=> We should test behavior when tasks don't get a valid executable

**Comment by tcompa** [comment]
I was not able to reproduce the precise error, and especially I did not see anything related to pickling.
However, with #800, we are adding a check that the task command is executable, and we fail with a `TaskExecutionError` otherwise.

Note: the check is performed in one of the functions which are executed by the actual user, and not by the `fractal` user. This is necessary, since the `fractal` user may have a different environment or different access rights.

In the new test, we submit a task with a non-executable command, and `job.log` looks like
```
TASK ERROR:Task id: 1 (invalid-task-command), e.workflow_task_order=0
TRACEBACK:
Command "/home/tommaso/Fractal/fractal-server/tests/data/non_executable_task.sh" is not valid. Hint: make sure that it is executable.
```
