### ISSUE TITLE
Remove automatic creation of default dataset when creating a project

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#674]
The project-creation endpoint also takes care of creating a first dataset. I think this feature gives us little benefit, since the dataset is anyway empty and it will have to be handled again later (e.g. to change its name/type or add resources). Also: this could be the input dataset for a workflow, but the output dataset still needs to be created.

In the same spirit of https://github.com/fractal-analytics-platform/fractal-server/issues/566, I propose to remove this feature. That is, a new project would be created without any dataset. The goal is to remove not-so-crucial branches, in order to:
* Simplify maintenance and documentation
* Make the addition of new features more transparent, instead of relying on some "hidden" feature.

Higher-level side note: there were good reasons for adding this kind of features in the first place, but IMO this is not the case any more after a few months of experience.

Any feedback? @jluethi @gusqgm

**Comment by jluethi** [comment]
Good discussion to have, I actually wanted to move in a separate direction. My observation during web demos was that there's still quite a few steps involved, e.g. going into the input dataset, modifying its name (optional), modifying its parameters (type image), adding resources. Creating an output dataset, modifying its parameters (type zarr), adding a resource. If we can reduce the number of steps needed here, that would be a big help.

As such, I was thinking about proposing:
1. The default dataset should be named "InputDataset"
2. The type of the "InputDataset" should be set to `image`
3. An "OutputDataset" should be automatically created
4. The type of the output dataset should be set to `zarr`

Currently, all workflows we have require such a setup. And we could reduce the required steps by the user to just: Add the  resources to input & output datasets (2 steps instead of 6).

Potentially, going forward, we could have different "project types", e.g. a blank project comes without any dataset, a Yokogawa project comes with those datasets, a Zarr project comes with input as OME-Zarr and different things in that direction. But for the current setup and for quite a while forward

**Comment by tcompa** [comment]
I think that the previous comments in this issue and the upcoming work in fractal-web (see https://github.com/fractal-analytics-platform/fractal-web/issues/299) all suggest that this issue is now ready for implementation.

### A side-comment
This is in line with ongoing work on https://github.com/fractal-analytics-platform/fractal-server/issues/826, as they both contribute to the high-level goal of keeping the CRUD endpoints as lightweight as possible and moving custom logic into dedicated endpoints. This may also make it simpler to create "complex" flows from fractal-web.

**Comment by tcompa** [comment]
To do:
1. Remove automatic dataset creation from project-creation endpoint
2. Fully remove `default_dataset_name` (e.g. from `ProjectCreate`)
3. This probably requires fixing a lot of test here
4. Update the client accordingly, and fix its tests (ref https://github.com/fractal-analytics-platform/fractal-client/issues/565)

**Comment by jluethi** [comment]
Will also require updating all the fractal-demos. Makes sense though, let's just keep track of that as well :)
