### ISSUE TITLE
Allow users to edit their own tasks

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-server#731]
Currently, editing tasks is restricted to superusers. I get a:

```
fractal task edit 10 --meta-file /path/to/meta_conversion.json 
ERROR:root:Server returned 403
ERROR:root:Original request: PATCH http://localhost:8011/api/v1/task/10
ERROR:root:Original payload: {"meta": {"parallelization_level": "image", "cpus_per_task": 2, "mem": 16000}}
ERROR:root:Server error message: {'detail': 'This action is restricted to superusers'}
```

That makes a lot of sense for common tasks. But user-specific tasks would be useful if they are editable by the user themselves.

**Comment by tcompa** [comment]
Here is the relevant part of the `patch_task` endpoint:
```python
async def patch_task(
    ...
    user: User = Depends(current_active_superuser),
) -> Optional[TaskRead]:
    ...
    # Check match of owner attribute. This check constitutes a preliminary,
    # **soft**, version of access control: if task owner differs from the
    # current user, we simply raise a warning. Note that this is not very
    # relevant as long as this endpoint is for superusers only
    if user.username:
        owner = user.username
    elif user.slurm_user:
        owner = user.slurm_user
    else:
        owner = None
    if owner != db_task.owner:
        logger.warning(
            f"Task owner ({db_task.owner}) differs "
            f"from current user ({owner}). Proceed anyway."
        )
    ...
```

The simple way to proceed is:
- [ ] Remove the superuser requirement;
- [ ] If `db_task.owner is None`, check that `user.is_superuser` and raise a 403 error ("forbidden") otherwise.
- [ ] If `db_task.owner is not None`, then transform the current warning into a 422 error ("unprocessable entity").

Let's keep in mind that this is not, strictly speaking, the right way to enforce access control. The combination of `username` and `slurm_user` is not meant to be unique, and part of it (the fall-back to `slurm_user`) is actually a workaround to make the admin life easier (but which has no meaning when a different backend is used).

To make it more explicit, let's implement this solution now, and it will most likely work fine for the moment, but it's still not an actual access-control setup. If we end up relying on it, or if we notice that users do use it a lot, then we should revisit this discussion and consider moving towards a more systematic option.

**Comment by jluethi** [comment]
Good summary & solution proposal. Agreed that this is not super clean, but this way seems like a good intermediate solution.

The only thing I'd add: It should always be possible for a super-user to edit any task, also tasks where db_task.owner is not None. In that way, if there are some edge cases where things don't match, we can still fall back on an admin user to change the tasks.

**Comment by tcompa** [comment]
> The only thing I'd add: It should always be possible for a super-user to edit any task, also tasks where db_task.owner is not None. In that way, if there are some edge cases where things don't match, we can still fall back on an admin user to change the tasks.

Agreed.
