### ISSUE TITLE
Replace `parallelization_level` with more structured options of what to run

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#792]
Just a dump of the meeting notes, for now:

Tasks which produce metadata will write a more structured list, e.g.

	B03/cycle1, well=B03, image_name=cycle1, *
	B03/cycle2, well=B03, image_name=cycle2, *

Or

    B03/cycle1/{relative_path_to_MIP}, well=B03, image_name=cycle1, relative_path_to_MIP
	

This gives access to the following component lists
- All current raw data
- A subset of them, e.g.
- A single well
- A single cycle for all wells
- A single cycle for a given well
- All 2D projections
- A subset of them, like above

NOTE: how to handle registration? The input would be the cycle that you want to register, and the task would take a reference_cycle parameter (which will be searched for in a standard path, i.e. “../reference_cycle”).

**Comment by jluethi** [comment]
> image_name

Is this the name of the folder in the well? e.g. 0 for plate_name.zarr/B/03/0?

> reference_cycle parameter (which will be searched for in a standard path, i.e. “../reference_cycle”)

To give an example here:
We have a task with 3 cycles:
B03/cycle1,
B03/cycle2, 
B03/cycle3,

The task would run separately for cycle 2 & cycle 3 (cycle 1 is a trivial registration to itself):
To run cycle 2, it gets the parameters to run on B03/cycle2 and the reference cycle B03/cycle1.
Path-wise, it could look like this:
Current component: plate_name.zarr/B/03/1
reference_cycle component: plate_name.zarr/B/03/0 

Or maybe it's always relative to the well folder, i.e. the info is just 0? Not sure. That would enable i.e. just saying the reference cycle is 0, then it works for 2D and 3D data, because it's relative to the component that the tasks gets (i.e. path for cycle2)

**Comment by jluethi** [comment]
My core idea is to split the selection of what is run into 3 categories:

- “Parallelization level”: Selection of whole plate vs. individual images at a time. Or new also selection for Dimensionality, registered vs. raw, Illumination corrected vs raw => different representations of the data that never need to be processed together. Typically, the new representation is the result of processing the raw data
- Component lists: A list for each parallelization level. Used for collection of OME-Zarrs, e.g. acquisitions, wells => different subsets of the dataset. 
- Subset of Zarrs: Subset selection of Zarrs are defined as task parameters. E.g. which ROI to loop over, which time point to process, which channel to load

TBD to specify this in more details (nested component list vs. arbitrary names of component lists, how tasks know when to switch to a different parallelization level / subset thereof.


See here for long-form brainstorming on the relevant component structure: https://docs.google.com/document/d/1J4-_HYbbaUdk6Wop0J7_hpGPX_QV4I8odzQeJfUNmuk/edit#heading=h.ji31nheqz584
