### ISSUE TITLE
Placeholder: do we need constraints on workflow execution?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#805]
This is a placeholder for something that came up as part of #793/#803, more on this later.
TLDR: can we re-run the N-th task of a workflow if we already ran the (N+1)-th one?

**Comment by jluethi** [comment]
Let's have the more in-depth discussion. We may want to put some guardrails on this. But I wouldn't say this should be generally impossible. Here's a use-case where we may want to support this:

A user ran raw data - Cellpose + measurements on the whole dataset. Then, they look at the whole output in napari and realize that for some image (e.g. in wells they didn't test in), the segmentation didn't perform well. In that case, they may do some broader testing and rerun cellpose + measurements.

This would require that cellpose & measurements can be rerun (i.e. the task is able to overwrite its own output, instead of failing if it already exists). But besides that, I wouldn't see larger issues with it.

**Comment by jluethi** [comment]
The place where it's not a good idea to rerun a task is when tasks change the actual image data. Currently only applies to illumination correction, may also be relevant for some multiplexing registration tasks.

Spontaneous idea: We could have those task set some metadata flag or some entry in the .zattrs. i.e. if the .zattrs contains an "illumination_correction: True" key somewhere, running the task fails
=> not a server logic that this task couldn't be rerun on specific data, but a task feature?

**Comment by jluethi** [comment]
Handled in Fractal V2 by tasks having required input types (e.g. illumination correction sets input filter for illum_corr = False)
